baseURL: "https://tombowyer.com/"
title: Tom Bowyer
paginate: 5
theme: PaperMod

disableKinds: ["taxonomy", "term"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: Tom Bowyer
  description: "Tom Bower - Software developer"
  keywords: [Blog, Portfolio, PaperMod]
  author: Tom Bowyer
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  search: true
  search_minify: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Tom Bowyer
    subtitle: "I like computers"
    imageUrl: "https://avatars.githubusercontent.com/u/24668318?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Myself

  socialIcons:
    - name: github
      url: "https://github.com/ImTheTom"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: Projects
      name: Projects
      url: /projects/
      weighting: 1
    - identifier: archive
      name: Archive
      url: /archive/
      weighting: 3
    - identifier: search
      name: Search
      url: /search/
      weighting: 4